### ISSUE TITLE
choosing link drops back to shell

### ISSUE THREAD

**Issue by verkaro** [codesoap/gmir#1]
Nice to find someone working on an offline gemini reader. Thank you.

I am a non-coding end-user. My feedback is best taken with a grain of salt.
I use debian and have tested in a bash shell and the elvish shell (why not? and they give me a consistant error)

Clicking a link via gmir spits out the link filename but drops me back to the cli.
Ready that grain of salt. It seems like the looping mechanism is broken. 

But to support the issue: 
All *.gmi doc links are within the same folder and I made the index myself.
Running gmifs on the folder confirms it to be a working structure.

I pulled the @latest version and built as suggested. go version go1.19.5 linux/amd64 running on a chromebook.

Hope this is uesful. And would you mind opening up a discussion tab on this repo? It's handy to comment on non-critical things without opening and issue report. I'll surely be following developments.

**Comment by codesoap** [comment]
Thanks for the early feedback, I'm happy to see there is interest in a GMI reader :-)

I probably need to explain this a little more in the README, but the behavior is as intended. It is not a goal of `gmir` to let you browse local files. When a link is selected within `gmir`, its URL will be printed as is to the terminal. This includes relative links like `blog-post.gmi`, absolute links like `/blog-post.gmi`, links to other capsules like `gemini://kennedy.gemi.dev` or even links to other protocols like `https://github.com`. The idea behind this is, that you can build tools like Gemini browsers but also local file browsers around `gmir`.

As a very rudimentary script to use `gmir` as a local file browser, you could use a script like this (not thoroughly tested):
```
#!/usr/bin/env sh

test $# -ne 1 \
&& printf 'Give exactly one file as an argument.\n' \
&& exit 1

prevURL=""
url="$1"
while url="$(gmir "$url")"; do
	test -z "$url" && exit 0
	if test "$(printf "$url" | cut -c1)" = "/"; then
		url="$(printf "$url" | cut -c2-)"
	else
		url="$(dirname "$prevURL")/$url"
	fi
	prevURL="$url"
done
```

You could probably also configure `xdg-open` to use `gmir` for GMI files and improve the script with that, but I haven't tried it yet. Maybe I'll publish a polished version of the above script in the future, but right now I'm still focusing on `gmir` itself.

Let me know if this helps!

PS: I have opened the discussions tab.

**Comment by verkaro** [comment]
Very good. And thanks for the clarity on gmir's purpose. Sounds good.
The shell script works fine for me. It's nice to browse my content on the spot. Thanks for that.
Cheers to ya.

**Comment by codesoap** [comment]
Glad the script works for you.

**Comment by verkaro** [comment]
I just compiled gmir on Windows this morning. Works fine. Can I ask a favor. I hope it's in your ballpark.
Do you know how to make a windows script that does the equivalent of the linux shell script you wrote earlier in this thread?
I appreciate it.

**Comment by codesoap** [comment]
Unfortunately I can't help you much with Windows, as I avoid this OS as much as possible. I believe that git comes with a bash shell on Windows, so maybe that's an option.

Alternatively I would probably turn to something like Python on Windows. Maybe something like this could work (I haven't tested in on Windows though; maybe you [need to throw a `os.path.abspath` in there](https://stackoverflow.com/q/25648256) or something similar to make Windows recognize the paths):
```python
#!/usr/bin/env python3

import os
import sys
import subprocess

if len(sys.argv) != 2:
	print("Give exactly one file as an argument.")
	exit(1)

path = sys.argv[1]
while True:
	prev_path = path
	gmir = subprocess.Popen(["gmir", path], stdout=subprocess.PIPE)
	path = gmir.stdout.read().decode("utf-8").strip()
	if path == "":
		break
	if os.path.isabs(path):
		path = path[1:]
	else:
		path = os.path.join(os.path.split(prev_path)[0], path)
```

**Comment by verkaro** [comment]
Thanks indeed. Yes, it's been almost twenty years since my last windows box but I am dealing with one now. I really appreciate the functional clarity and performance I've gotten from Linux in comparison. I'll install python and git it a go. Thanks again.
